### ISSUE TITLE
Cannot get the password hash to repeat per user

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/password_policy_history#1]

**Comment by nerdstein** [comment]
The Password manager appears to be changing this hash over time. This means that any persistent storage of the password may also need the password hash stored persistently.

**Comment by lahoosascoots** [comment]
So as the password is salted you wont get the same hash each time.

This means when checking to see if the password has been used before, you'll need to run \Drupal::service('password')->check() against every password they've had.

**Comment by lahoosascoots** [comment]
Committed what _should_ work. Need to wait on the Validation bug in password policy to check it though.

**Comment by nerdstein** [comment]
Awesome!!

I'll review now

**Comment by nerdstein** [comment]
Aweesome!!!!!!

**Comment by nerdstein** [comment]
Leaving open for testing once we unblock pp

**Comment by lahoosascoots** [comment]
PR #4 should get everything working now that PP works.
